### ISSUE TITLE
jni4net licensing query

### ISSUE THREAD

**Issue by madhavinaik** [jni4net/jni4net#18]
Is there anything (a document or wiki) that states when either of those two (GPLv3 or MIT) licenses are applicable?, i.e. 

1.	When is the jni4net license actually in force – is there an article you can share with me that clearly explains this?
2.	Is there anything that discounts the derivative output code created by ProxyGen to state that it is not also applicable to GPL, or does a document/wiki clearly state that derivative proxies are covered by the MIT runtime license?

**Comment by pavelsavara** [comment]
I'm not a lawyer!

Generally GPLv3 applies to the code of the proxygen tool, anything else in this repository is MIT licensed. Most files file have license in it's header.

The product of proxygen is not licensed at all, as far as I am concerned. In my opinion proxygen is similar to compilers, it just transforms the code and metadata. The produced proxies may be affected by the license of the original API you used to generate them.
