### ISSUE TITLE
jni4net why java.util.List no implementation? How to implement?

### ISSUE THREAD

**Issue by taotao2014** [jni4net/jni4net#20]
I was wondering why there is no implementation for the java.util.List interface in the jni4net DLL? Am I missing something?

There are Dictionary and Hashtable classes, but no implementation for List or Set. No big deal, just curious. Is there a reason for that?

Thanks

**Comment by pavelsavara** [comment]
Feel free to provide fix for that.

**Comment by taotao2014** [comment]
What does this mean? Will the solution there?  How to implement  java.util.List ?

**Comment by pavelsavara** [comment]
I do not plan to work on it myself. If you seek advice how to improve this project, I suggest that you first start exploring it's source code and then ask smart questions as defined below :
http://www.catb.org/esr/faqs/smart-questions.html

**Comment by taotao2014** [comment]
Thank you very much, , because more anxiety this problem, I look at the source code , thank you.
