### ISSUE TITLE
Unable to call vb.net dll in Java using JNI4NET 

### ISSUE THREAD

**Issue by rajeshkumarpenugonda** [jni4net/jni4net#21]
I am New to vb.net and i want to use existing vb.net code in to my java application for that i choose your jni4net and i am using windows 32 bit operating system.

step 1 : created a library project in vb.net
step 2 : created a dll for that project
step 3 : downloaded the jni4net-0.8.8.0-bin.zip
step 4 : follow the steps https://github.com/jni4net/jni4net/wiki/
step 5 : created a java project in eclipse and try to execute but i am facing following exception.

loading core from D:/Rajesh/JNI4NET/jni4net.n-0.8.8.0.dll
loading jni4net.n-0.8.8.0, Version=0.8.8.0, Culture=neutral, PublicKeyToken=134a23405600bab4 from D:\Rajesh\JNI4NET\jni4net.n-0.8.8.0.dll
loaded jni4net.n-0.8.8.0, Version=0.8.8.0, Culture=neutral, PublicKeyToken=134a23405600bab4 from D:\Rajesh\JNI4NET\jni4net.n-0.8.8.0.dll
Initialized jni4net core
core loaded from D:/Rajesh/JNI4NET/jni4net.n-0.8.8.0.dll
clr.version         :v4.0.30319
clr.arch            :32bit
java.home           :C:\Program Files\Java\jre1.8.0_60
java.version        :1.8.0_60
sun.arch.data.model :32
loading SimpleDll.j4n, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from C:\BhushanProg\SabreWork\Jni4Net\SimpleDll.j4n.dll
loaded SimpleDll.j4n, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from C:\BhushanProg\SabreWork\Jni4Net\SimpleDll.j4n.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: simpledll.Sample.__ctorSample0(Lnet/sf/jni4net/inj/IClrProxy;)V
	at simpledll.Sample.__ctorSample0(Native Method)
	at simpledll.Sample.<init>(Sample.java:25)
	at Jni4NetTest.main(Jni4NetTest.java:22)

![jni4nettest](https://cloud.githubusercontent.com/assets/14233760/9813874/020545e0-58a7-11e5-91b5-8decc986831c.png)

Please help me and thanks in advance

**Comment by rajeshkumarpenugonda** [comment]
Hi to all,
I am unable to execute using eclipse but 
![jni4test](https://cloud.githubusercontent.com/assets/14233760/9869832/a8daa400-5ba4-11e5-8d4d-d1499c664289.jpg)
execute the above code from command prompt from windows.

Steps :
1.Created proxy files(using vb.net dll (SimpleDll.dll))
2. write java program.(Jni4NetTest.java)
3. copy proxy files and jar files in one folder
4.compile the java program
Ex:-
D:\Rajesh\jni4net>javac -d .\ -cp .\jni4net-0.8.8.0.jar;.\SimpleDll.j4n.jar Jni4NetTest.java

5.Run the java program
Ex:-
D:\Rajesh\jni4net>java -cp jni4net-0.8.8.0.jar;SimpleDll.j4n.jar;. Jni4NetTest

 Please help me and thanks in advance
![jni4test](https://cloud.githubusercontent.com/assets/14233760/9869844/bf7a212c-5ba4-11e5-9687-d1548b7db448.jpg)

**Comment by pavelsavara** [comment]
this is not support forum
http://jni4net.com/troubleshoot.html

**Comment by rajeshkumarpenugonda** [comment]
Hi Pavelsavara,
Thanks for your response.Now able to execute my eclipse application followed by this video link.
https://www.youtube.com/watch?v=tI0tFUjeffA (Using Jni4Net) from 25:14 mins onwards.

Thanks&Regrads,
P Rajesh Kumar
