### ISSUE TITLE
build command execution failed with errors while running build.cmd to generate xxx.j4n.dll

### ISSUE THREAD

**Issue by ankit0204** [jni4net/jni4net#23]
Hi..I am trying to run c# method from Java using jni4net. I followed all the steps which mentioned in the guide. I am able to generate proxy file to run proxygen.exe. 

After running proxygen.exe I am getting :

1. clr/namespace/.cs file 
2. jvm/namespace/.java file
3. build.cmd
4. xxx.proxygen.xml file

but I am getting also getting several errors in the next step while running build.cmd. After running build.cmd it is creating xxx.j4n.jar file but giving errors for xxx.j4n.dll. It is giving errors in .cs file which got generated in previous step ( run proxygen.exe step). For your reference I am sending the screenshot of errors.

How can I resolve this issue ? Please help me on this.

![error](https://cloud.githubusercontent.com/assets/15361824/10789134/93ef1ad4-7da1-11e5-9995-aa782dec0bb3.JPG)

**Comment by OlegRa** [comment]
Could you please post generated code? Most probably your sample tries to use some .NET features which not supported by JNI4NET.

**Comment by ankit0204** [comment]
@OlegRa Please check the generated code.

Generated files - 

**clr/csharphelloworld/SharpHelloWorld.generated.cs :**

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
    //     Runtime Version:4.0.30319.269
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace CSharpHelloWorld {
    
    
    #region Component Designer generated code 
    public partial class SharpHelloWorld_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CSharpHelloWorld.@__SharpHelloWorld.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CSharpHelloWorld.SharpHelloWorld), typeof(global::CSharpHelloWorld.SharpHelloWorld_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CSharpHelloWorld.SharpHelloWorld), typeof(global::CSharpHelloWorld.SharpHelloWorld_))]
    internal sealed partial class @__SharpHelloWorld : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__SharpHelloWorld(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CSharpHelloWorld.@__SharpHelloWorld.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SharpHelloWorld);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "displayHelloWorld", "displayHelloWorld0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSharpHelloWorld0", "__ctorSharpHelloWorld0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static void displayHelloWorld0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CSharpHelloWorld.SharpHelloWorld.displayHelloWorld();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSharpHelloWorld0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CSharpHelloWorld.SharpHelloWorld @__real = new global::CSharpHelloWorld.SharpHelloWorld();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CSharpHelloWorld.@__SharpHelloWorld(@__env);
            }
        }
    }
    #endregion
     }




**jvm/csharphelloworld/SharpHelloWorld.java - **

    // ------------------------------------------------------------------------------
    //  <autogenerated>
    //      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
    // 
    //      Changes to this file may cause incorrect behavior and will be lost if 
    //      the code is regenerated.
    //  </autogenerated>
    // ------------------------------------------------------------------------------

    package csharphelloworld;

    @net.sf.jni4net.attributes.ClrType
    public class SharpHelloWorld extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SharpHelloWorld(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public SharpHelloWorld() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        csharphelloworld.SharpHelloWorld.__ctorSharpHelloWorld0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorSharpHelloWorld0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void displayHelloWorld();
    
    public static system.Type typeof() {
        return csharphelloworld.SharpHelloWorld.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        csharphelloworld.SharpHelloWorld.staticType = staticType;
    }
    //</generated-proxy>
    }



** build.cmd**

    @echo off
    if not exist target mkdir target
    if not exist target\classes mkdir target\classes

    set PATH=%PATH%;C:\Program     
    Files\Java\jdk1.7.0_07\bin;C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705

    echo compile classes
    javac -nowarn -d target\classes -sourcepath jvm -cp "d:\ankit\jni4net-0.8.8.0-bin\lib\jni4net.j-    
    0.8.8.0.jar"; "jvm\csharphelloworld\SharpHelloWorld.java" 
    IF %ERRORLEVEL% NEQ 0 goto end


    echo CSharpHelloWorld.j4n.jar 
    jar cvf CSharpHelloWorld.j4n.jar  -C target\classes "csharphelloworld\SharpHelloWorld.class"  > nul 
    IF %ERRORLEVEL% NEQ 0 goto end


    echo CSharpHelloWorld.j4n.dll 
    csc /nologo /warn:0 /t:library /out:CSharpHelloWorld.j4n.dll /recurse:clr\*.cs     
    /reference:"C:\Documents and Settings\Administrator\workspace\NativeTest\CSharpHelloWorld.dll"    
    /reference:"D:\Ankit\jni4net-0.8.8.0-bin\lib\jni4net.n-0.8.8.0.dll"
    IF %ERRORLEVEL% NEQ 0 goto end


    :end


**project structure - **

![structure](https://cloud.githubusercontent.com/assets/15361824/10810905/fc6f2286-7e2b-11e5-9b22-fa9ca8aead4e.JPG)

**Comment by OlegRa** [comment]
JNI4NET generates code for .NET 2.0 and higher but you try to compile it using C# compiler from .NET 1.0 - this compiler doesn't support some features/keywords from generated code.

 Replace line:

`set PATH=%PATH%;C:\Program Files\Java\jdk1.7.0_07\bin;C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705`

 with something like:

`set PATH=%PATH%;C:\Program Files\Java\jdk1.7.0_07\bin;C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727`

 or better use .NET version number corresponding to .NET version used by your C# project.

**Comment by ankit0204** [comment]
I changed the path and given v2.0.50727 but still giving same errors.

**Comment by OlegRa** [comment]
Please, remove /nologo option form csc.exe call and send output in text form - it's not so easy to find problem using screenshot.

**Comment by ankit0204** [comment]
Errors While running build.cmd -

    compile classes
    CSharpHelloWorld.j4n.jar 
    CSharpHelloWorld.j4n.dll 
    Microsoft (R) Visual C# .NET Compiler version 7.00.9466
    for Microsoft (R) .NET Framework version 1.0.3705
    Copyright (C) Microsoft Corporation 2001. All rights reserved.

    clr\csharphelloworld\SharpHelloWorld.generated.cs(15,12): error CS1518: Expected class,   
    delegate, enum, interface, or struct
    clr\csharphelloworld\SharpHelloWorld.generated.cs(17,29): error CS1519: Invalid token ':' in class,   
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(26,13): error CS0658: 'global' is not a valid   
    attribute location
    clr\csharphelloworld\SharpHelloWorld.generated.cs(27,13): error CS0658: 'global' is not a valid 
    attribute location
    clr\csharphelloworld\SharpHelloWorld.generated.cs(28,21): error CS1518: Expected class,     
    delegate, enum, interface, or struct
    clr\csharphelloworld\SharpHelloWorld.generated.cs(28,62): error CS1514: { expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(28,81): error CS1519: Invalid token '{' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(30,35): error CS1519: Invalid token ':' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(32,42): error CS1001: Identifier expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(32,43): error CS1018: Keyword this or base  
    expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(32,76): error CS1002: ; expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(33,28): error CS1519: Invalid token ')' in class,  
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(36,43): error CS1001: Identifier expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(36,83): error CS1002: ; expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(36,103): error CS1002: ; expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(37,19): error CS1519: Invalid token ':' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(37,69): error CS1519: Invalid token '=' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(37,79): error CS1519: Invalid token ';' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(40,9): error CS0116: A namespace does not 
    directly contain members such as fields or methods
    clr\csharphelloworld\SharpHelloWorld.generated.cs(67,61): error CS1514: { expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(67,104): error CS1519: Invalid token '{' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(69,26): error CS1519: Invalid token ':' in class,   
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(69,75): error CS1001: Identifier expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(69,109): error CS1002: ; expected
    clr\csharphelloworld\SharpHelloWorld.generated.cs(70,34): error CS1519: Invalid token ':' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(70,71): error CS1519: Invalid token '(' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(70,78): error CS1519: Invalid token ')' in class, 
    struct, or interface member declaration
    clr\csharphelloworld\SharpHelloWorld.generated.cs(73,5): error CS1022: Type or namespace 
    definition, or end-of-file expected

**Comment by ankit0204** [comment]
@OlegRa  Thanks for your suggestion. Now I am able to generate xxx.j4n.dll file. As you suggested I changed the .net version. Earlier I was changing in build.cmd file but now I changed in environmental variable so buil.cmd ran successfully.

But after that I am getting another issue. I imported all the dll files into my project and getting error in Java file ( csharphelloworld.SharpHelloWorld.displayHelloWorld(); ). Could you please have a look on java file. How can I call the c# method from here. What is the syntax.

 I am posting my project structure and Java file.

**Java file -**

    import java.io.File;
    import java.io.IOException;
 
    import net.sf.jni4net.Bridge;


    public class JNI4NetTest {

	public static void main(String[] args) {
		
		try {
		Bridge.setVerbose(true);
		
		Bridge.init();
		
		File proxyAssemblyFile = new File("CSharpHelloWorld.j4n.dll");
		
		Bridge.LoadAndRegisterAssemblyFrom(proxyAssemblyFile);
		
           // calling c# method displayHelloWorld() in SharpHelloWorld class in csharphelloworld   
          //  package
		csharphelloworld.SharpHelloWorld.displayHelloWorld();

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	  }
    }


**project structure -**

![proj structure](https://cloud.githubusercontent.com/assets/15361824/10812690/d6b9f7b0-7e3e-11e5-819c-036bc8e379d7.JPG)

**Comment by ankit0204** [comment]
@OlegRa Thanks for your suggestion. Now I am able to generate xxx.j4n.dll file. Earlier I was changing .net version in build.cmd file but now I changed .net version in environmental variable and worked fine and getting output in Java console.
Thank you very much.

**Comment by ankit0204** [comment]
@OlegRa I have executed the code on windows machine. Is there any way that I can execute this c sharp code from java on ubuntu ?

**Comment by OlegRa** [comment]
JNI4NET doesn't officially support Mono or .NET Core. So short answer - no. But you can try to implement this support :)

**Comment by ankit0204** [comment]
I will try :)
Thanks.
