### ISSUE TITLE
How to use the binaries in a Maven project

### ISSUE THREAD

**Issue by birgersp** [jni4net/jni4net#32]
Hi,

I'm clueless how to get jni4net working in my Maven project. The project is able to find the .jar files but I get the following exception when I try to run it:

> Exception in thread "main" net.sf.jni4net.inj.INJException: Can't initialize jni4net Bridge
> 	at net.sf.jni4net.CLRLoader.init(CLRLoader.java:45)
> 	at net.sf.jni4net.Bridge.init(Bridge.java:35)
> 	at net.sf.jni4net.Bridge.init(Bridge.java:31)
> 	at no.offsim.ntnu.abcontrol.Main.main(Main.java:37)
> Caused by: java.lang.UnsatisfiedLinkError: net.sf.jni4net.Bridge.initDotNet()I
> 	at net.sf.jni4net.Bridge.initDotNet(Native Method)
> 	at net.sf.jni4net.CLRLoader.init(CLRLoader.java:37)

**Comment by pavelsavara** [comment]
For support please use StackOverflow instead.
