### ISSUE TITLE
Initializing bridge attempts to load a library with the same name as my project jar

### ISSUE THREAD

**Issue by birgersp** [jni4net/jni4net#33]
Hi,

I've tried to install jni4net to my maven repository like so:

`mvn install:install-file -DlocalRepositoryPath=%temp_repo_dir% -DcreateChecksum=true -Dpackaging=jar -Dfile=%proxygen_dir%/jni4net.j-0.8.8.0.jar -DgroupId=jni4net -DartifactId=jni4net.j -Dversion=0.8.8.0`

In my projects pom.xml, I've added the following:

```
<repositories>
    <repository>
        <id>repo</id>
        <url>file://${project.basedir}/temp-repo</url>
    </repository>
</repositories>
    
<dependencies>
    <dependency>
        <groupId>jni4net</groupId>
        <artifactId>jni4net.j</artifactId>
        <version>0.8.8.0</version>
    </dependency>
</dependencies>
```

> Exception in thread "main" net.sf.jni4net.inj.INJException: Can't initialize jni4net Bridge
>         at net.sf.jni4net.CLRLoader.init(CLRLoader.java:45)
>         at net.sf.jni4net.Bridge.init(Bridge.java:35)
>         at net.sf.jni4net.Bridge.init(Bridge.java:31)
>         at no.offsim.ntnu.abcontrol.AbleBodyController.init(AbleBodyController.java:24)
>         at no.offsim.ntnu.abcontrol.Main.<init>(Main.java:46)
>         at no.offsim.ntnu.abcontrol.Main.main(Main.java:36)
> Caused by: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Birger\Workspace\myproject\abcontrol\target\abcontrol-1.0-SNAPSHOT-shaded.dll
>         at java.lang.ClassLoader.loadLibrary(Unknown Source)
>         at java.lang.Runtime.load0(Unknown Source)
>         at java.lang.System.load(Unknown Source)
>         at net.sf.jni4net.CLRLoader.init(CLRLoader.java:36)
>         ... 5 more

Why is the application trying to load a .dll with the name of my jar? It should obviously try to load `jni4net.n-0.8.8.0.dll`

**Comment by pavelsavara** [comment]
For support please use StackOverflow instead.

**Comment by truongduykhanh36** [comment]
I've had the same problem, and I tried this
https://stackoverflow.com/questions/46496052/java-jni4net-bridge-deploying-jar-with-dll-dependenices
worked for me.
