### ISSUE TITLE
Getting "jni4net.n-0.8.8.0.dll: Can't load this .dll (machine code=0xbd) on a AMD 64-bit platform"

### ISSUE THREAD

**Issue by birgersp** [jni4net/jni4net#36]
No matter which JVM I try to launch my application (using jni4net) with, I cannot load the "jni4net.n-0.8.8.0.dll" library, as it yields:

`Can't load this .dll (machine code=0xbd) on a AMD 64-bit platform`
or
`Can't load this .dll (machine code=0xbd) on a IA 32-bit platform`

**Comment by pavelsavara** [comment]
http://jni4net.com/troubleshoot.html
