### ISSUE TITLE
jni4net Trying to load a Library that doesnt exist

### ISSUE THREAD

**Issue by kyle-oshaughnessy** [jni4net/jni4net#38]
I built a simple C# dll that only has a hello world method (Built with .NET v3.5). I followed the instructions on the wiki:

- I Ran proxygen.exe on my C# dll: It produced all the files described in the wiki
- I Ran build.cmd: It produced all the files described in the wiki
- I stored all the needed files in the root directory of my project and added my dll jar (dllTest.j4n.jar) and jni4net.j-0.8.8.0.jar to the build path. (Note: I'm running eclipse on linux but everything else was done on windows)

![image](https://cloud.githubusercontent.com/assets/15810643/18690936/e1efe8a2-7f5e-11e6-8c21-3c715fdd29c5.png)

*I tried downgrading to jni4net 0.8.3.0 and had the same issues (See below)

I'm having 2 problems: 
1.  Although the dll jar is being read and recognizes my C# method (It autocompleted dll.Class1.printTest() for me), java still reports that "The import dllTest cannot be resolved"
2. Wen I run the java project, java reports "Can't Initialize BridgeCan't Load Library: <workspace>/jni4net.n.164.m26-0.8.3.0.dll"  --> This is no surprise because that file doesn't exist, but I have no control over which file Bridge.init() looks for. Does anybody know what I might be doing wrong?

**Comment by kyle-oshaughnessy** [comment]
Follow Up:

I know that Jni4net is designed only for Windows (not Linux) but I thought that by compiling the proxies (proxygen and build.cmd) on Windows, I could include the produced dlls and jars in my Eclipse project on Linux and it would still work. Is this correct, or do the dlls only work on Windows for some reason?

**Comment by pavelsavara** [comment]
only on windows

On Wed, Sep 21, 2016 at 4:26 PM, kyle-oshaughnessy <notifications@github.com

**Comment by kyle-oshaughnessy** [comment]
Ok thanks. Do you know of any options for Linux?

**Comment by pavelsavara** [comment]
http://jni4net.com/links.html

On Wed, Sep 21, 2016 at 5:20 PM, kyle-oshaughnessy <notifications@github.com
