### ISSUE TITLE
Utilizing third party .jar files.  Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by brianushman** [jni4net/jni4net#78]
I've built a library in Eclipse that exposes methods from a vendor/third party set of jars.  When I exported my jar from Eclipse I chose to export as a "runnable jar" and copying required libraries into a sub-folder next to the generated jar.  So after exporting, I see my jar with all my vendor jar next copied into the sub-folder.

As a test, I ran my exported jar in java and it executed as expected.  I generated my .net dll from this .jar and imported the generated dll/jar files into my .net solution.  When I run my example, I get the exception: "Exception has been thrown by the target of an invocation.". The inner exception indicates that there was a problem with one of the third party jar files.  The exception message just lists the class name, doesn't say what the problem is.  So I wondered, since this third party class didn't get exported to .net, could that be the problem?  But it seems it shouldn't be.

What I'm trying to do is the following:
classA.java (contains method which class method in classB)
classB.jar (this is a jar file I don't own but reference).

When I create my classA.jar, I am only exporting data for classA, and then I have classB.jar in a sub-folder next to my generated jar.  However, in .NET when I run my example, I get the error: "java.lang.NoClassDefFoundError".  Is there a way to get this to work without having to either build my third party .jar files into mine or having to use the proxy generator to also include these jars?  I thought that once the call I'm making is in the JVM, it should then work without having exported the other jar's to the .net bindings.

Thank you!

**Comment by marcabrus** [comment]
did you manage to overcome this situation? I have the same problem
